services:
  serverpart6:
    build: ./serverpart5/
    container_name: serverpart6
    volumes:
      - ./serverpart5/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - localnet


  proxypart6:
    build: ./proxy/
    container_name: proxypart6
    ports:
      - 80:8080
    networks:
      - localnet

networks:
  localnet:
    name: localnet
    driver: bridge
